### ISSUE TITLE
Make all columns sortable

### ISSUE THREAD

**Issue by drewpearce** [ReformedDevs/anonbot#1]
Please make all columns sortable, not just the Votes.

**Comment by nathan-osman** [comment]
What other columns do you want to sort by?

**Comment by nathan-osman** [comment]
Hmm... I suppose author.

**Comment by drewpearce** [comment]
author and twitter account (for if you have more than 1)

**Comment by nathan-osman** [comment]
It sorts by Twitter account by default: https://github.com/ReformedDevs/anonbot/blob/master/server/suggestions.go#L15

**Comment by drewpearce** [comment]
Should you make it toggle-able as well? If I go to sort by something else, I can't get back to that view without editing the URL.

**Comment by nathan-osman** [comment]
Hmm... that is a good point.
